import 'models.dart';

// Imported from the FitLife Lovable workout catalogue (96 offline routines).
final workouts = <Workout>[
  Workout(id: 'beginner-first-steps', name: 'First Steps', category: 'Beginner', difficulty: 'Beginner', minutes: 4, calories: 51, description: 'A gentle introduction to moving your whole body. Perfect for day one.', exercises: <String>['March In Place', 'Step Touch', 'Bodyweight Squats', 'Knee Push Ups', 'Glute Bridges']),
  Workout(id: 'beginner-beginner-full-body', name: 'Beginner Full Body', category: 'Beginner', difficulty: 'Beginner', minutes: 5, calories: 61, description: 'The classic starter routine hitting every major muscle group.', exercises: <String>['Knee Push Ups', 'Glute Bridges', 'Crunches', 'Plank', 'Arm Circles', 'Calf Raises']),
  Workout(id: 'beginner-easy-morning-wake-up', name: 'Easy Morning Wake Up', category: 'Beginner', difficulty: 'Beginner', minutes: 4, calories: 51, description: 'Light movement to shake off sleep and start the day well.', exercises: <String>['Plank', 'Arm Circles', 'Calf Raises', 'Dead Bug', 'Bird Dog']),
  Workout(id: 'beginner-gentle-strength-start', name: 'Gentle Strength Start', category: 'Beginner', difficulty: 'Beginner', minutes: 5, calories: 61, description: 'Build a base of strength with simple, controlled movements.', exercises: <String>['Dead Bug', 'Bird Dog', 'Wall Sit', 'Superman', 'Shoulder Rolls', 'Reverse Lunges']),
  Workout(id: 'beginner-beginner-core-basics', name: 'Beginner Core Basics', category: 'Beginner', difficulty: 'Beginner', minutes: 4, calories: 51, description: 'Learn to brace your core safely with foundational holds.', exercises: <String>['Superman', 'Shoulder Rolls', 'Reverse Lunges', 'March In Place', 'Step Touch']),
  Workout(id: 'beginner-low-impact-starter', name: 'Low Impact Starter', category: 'Beginner', difficulty: 'Beginner', minutes: 5, calories: 61, description: 'No jumping at all â€” kind to knees and downstairs neighbours.', exercises: <String>['March In Place', 'Step Touch', 'Bodyweight Squats', 'Knee Push Ups', 'Glute Bridges', 'Crunches']),
  Workout(id: 'beginner-confidence-builder', name: 'Confidence Builder', category: 'Beginner', difficulty: 'Beginner', minutes: 6, calories: 71, description: 'A slightly longer session to prove to yourself you can do it.', exercises: <String>['Knee Push Ups', 'Glute Bridges', 'Crunches', 'Plank', 'Arm Circles', 'Calf Raises', 'Dead Bug']),
  Workout(id: 'beginner-beginner-strength-circuit', name: 'Beginner Strength Circuit', category: 'Beginner', difficulty: 'Beginner', minutes: 6, calories: 71, description: 'Simple circuit format with generous rest between exercises.', exercises: <String>['Plank', 'Arm Circles', 'Calf Raises', 'Dead Bug', 'Bird Dog', 'Wall Sit', 'Superman']),
  Workout(id: 'beginner-desk-break-reset', name: 'Desk Break Reset', category: 'Beginner', difficulty: 'Beginner', minutes: 4, calories: 51, description: 'A short movement break for long days at a desk.', exercises: <String>['Dead Bug', 'Bird Dog', 'Wall Sit', 'Superman', 'Shoulder Rolls']),
  Workout(id: 'beginner-beginner-progression', name: 'Beginner Progression', category: 'Beginner', difficulty: 'Intermediate', minutes: 8, calories: 96, description: 'Ready for a bit more? A step up from the beginner basics.', exercises: <String>['Superman', 'Shoulder Rolls', 'Reverse Lunges', 'March In Place', 'Step Touch', 'Bodyweight Squats', 'Knee Push Ups', 'Glute Bridges']),
  Workout(id: 'full-body-total-body-blast', name: 'Total Body Blast', category: 'Full Body', difficulty: 'Intermediate', minutes: 8, calories: 96, description: 'A balanced full body circuit that leaves nothing untrained.', exercises: <String>['Squat Jumps', 'Tricep Dips', 'Jumping Jacks', 'Bodyweight Squats', 'Push Ups', 'Lunges', 'Plank', 'Mountain Climbers']),
  Workout(id: 'full-body-full-body-foundations', name: 'Full Body Foundations', category: 'Full Body', difficulty: 'Beginner', minutes: 5, calories: 61, description: 'The essential movement patterns: squat, push, hinge, brace.', exercises: <String>['Bodyweight Squats', 'Push Ups', 'Lunges', 'Plank', 'Mountain Climbers', 'Glute Bridges']),
  Workout(id: 'full-body-metabolic-full-body', name: 'Metabolic Full Body', category: 'Full Body', difficulty: 'Advanced', minutes: 10, calories: 135, description: 'Short rests and big movements to keep the heart rate high.', exercises: <String>['Plank', 'Mountain Climbers', 'Glute Bridges', 'Burpees', 'Russian Twists', 'Superman', 'High Knees', 'Wall Sit', 'Pike Push Ups']),
  Workout(id: 'full-body-30-minute-full-body', name: '30 Minute Full Body', category: 'Full Body', difficulty: 'Intermediate', minutes: 10, calories: 120, description: 'A longer complete session when you have time to spare.', exercises: <String>['Burpees', 'Russian Twists', 'Superman', 'High Knees', 'Wall Sit', 'Pike Push Ups', 'Bicycle Crunches', 'Squat Jumps', 'Tricep Dips', 'Jumping Jacks']),
  Workout(id: 'full-body-full-body-power', name: 'Full Body Power', category: 'Full Body', difficulty: 'Advanced', minutes: 9, calories: 120, description: 'Explosive movements for athletic strength and conditioning.', exercises: <String>['High Knees', 'Wall Sit', 'Pike Push Ups', 'Bicycle Crunches', 'Squat Jumps', 'Tricep Dips', 'Jumping Jacks', 'Bodyweight Squats']),
  Workout(id: 'full-body-express-full-body', name: 'Express Full Body', category: 'Full Body', difficulty: 'Beginner', minutes: 4, calories: 51, description: 'Everything that matters, compressed into a quick session.', exercises: <String>['Bicycle Crunches', 'Squat Jumps', 'Tricep Dips', 'Jumping Jacks', 'Bodyweight Squats']),
  Workout(id: 'full-body-strength-endurance-mix', name: 'Strength Endurance Mix', category: 'Full Body', difficulty: 'Intermediate', minutes: 8, calories: 96, description: 'Alternating strength holds and moving exercises.', exercises: <String>['Jumping Jacks', 'Bodyweight Squats', 'Push Ups', 'Lunges', 'Plank', 'Mountain Climbers', 'Glute Bridges', 'Burpees']),
  Workout(id: 'full-body-full-body-burn', name: 'Full Body Burn', category: 'Full Body', difficulty: 'Advanced', minutes: 10, calories: 135, description: 'High effort session for experienced trainees.', exercises: <String>['Lunges', 'Plank', 'Mountain Climbers', 'Glute Bridges', 'Burpees', 'Russian Twists', 'Superman', 'High Knees', 'Wall Sit']),
  Workout(id: 'full-body-balanced-body-circuit', name: 'Balanced Body Circuit', category: 'Full Body', difficulty: 'Intermediate', minutes: 7, calories: 84, description: 'Push, pull and legs in a smooth repeating circuit.', exercises: <String>['Glute Bridges', 'Burpees', 'Russian Twists', 'Superman', 'High Knees', 'Wall Sit', 'Pike Push Ups']),
  Workout(id: 'full-body-weekend-warrior', name: 'Weekend Warrior', category: 'Full Body', difficulty: 'Intermediate', minutes: 9, calories: 108, description: 'A satisfying longer workout for your day off.', exercises: <String>['Superman', 'High Knees', 'Wall Sit', 'Pike Push Ups', 'Bicycle Crunches', 'Squat Jumps', 'Tricep Dips', 'Jumping Jacks', 'Bodyweight Squats']),
  Workout(id: 'cardio-cardio-kickstart', name: 'Cardio Kickstart', category: 'Cardio', difficulty: 'Beginner', minutes: 5, calories: 61, description: 'An approachable cardio session to build your engine.', exercises: <String>['Fast Feet', 'Star Jumps', 'Jump Rope Mime', 'Step Touch', 'March In Place', 'Jumping Jacks']),
  Workout(id: 'cardio-hiit-express', name: 'HIIT Express', category: 'Cardio', difficulty: 'Advanced', minutes: 8, calories: 120, description: 'Short bursts of maximum effort with minimal rest.', exercises: <String>['Step Touch', 'March In Place', 'Jumping Jacks', 'High Knees', 'Butt Kicks', 'Burpees', 'Mountain Climbers', 'Skater Jumps']),
  Workout(id: 'cardio-fat-burn-circuit', name: 'Fat Burn Circuit', category: 'Cardio', difficulty: 'Intermediate', minutes: 7, calories: 96, description: 'Steady, continuous work to keep your heart rate elevated.', exercises: <String>['High Knees', 'Butt Kicks', 'Burpees', 'Mountain Climbers', 'Skater Jumps', 'Squat Jumps', 'Shadow Boxing', 'Fast Feet']),
  Workout(id: 'cardio-low-impact-cardio', name: 'Low Impact Cardio', category: 'Cardio', difficulty: 'Beginner', minutes: 5, calories: 61, description: 'Get your heart rate up with no jumping at all.', exercises: <String>['Mountain Climbers', 'Skater Jumps', 'Squat Jumps', 'Shadow Boxing', 'Fast Feet', 'Star Jumps']),
  Workout(id: 'cardio-boxing-conditioning', name: 'Boxing Conditioning', category: 'Cardio', difficulty: 'Intermediate', minutes: 6, calories: 84, description: 'Punch, move and breathe your way to better conditioning.', exercises: <String>['Shadow Boxing', 'Fast Feet', 'Star Jumps', 'Jump Rope Mime', 'Step Touch', 'March In Place', 'Jumping Jacks']),
  Workout(id: 'cardio-sprint-intervals', name: 'Sprint Intervals', category: 'Cardio', difficulty: 'Advanced', minutes: 8, calories: 120, description: 'Repeat all-out efforts with short recoveries.', exercises: <String>['Jump Rope Mime', 'Step Touch', 'March In Place', 'Jumping Jacks', 'High Knees', 'Butt Kicks', 'Burpees', 'Mountain Climbers']),
  Workout(id: 'cardio-cardio-core-combo', name: 'Cardio Core Combo', category: 'Cardio', difficulty: 'Intermediate', minutes: 7, calories: 96, description: 'Cardio bursts paired with core work.', exercises: <String>['Jumping Jacks', 'High Knees', 'Butt Kicks', 'Burpees', 'Mountain Climbers', 'Skater Jumps', 'Squat Jumps', 'Shadow Boxing']),
  Workout(id: 'cardio-morning-heart-starter', name: 'Morning Heart Starter', category: 'Cardio', difficulty: 'Beginner', minutes: 4, calories: 51, description: 'Five minutes of movement to wake up your system.', exercises: <String>['Burpees', 'Mountain Climbers', 'Skater Jumps', 'Squat Jumps', 'Shadow Boxing']),
  Workout(id: 'cardio-endurance-builder', name: 'Endurance Builder', category: 'Cardio', difficulty: 'Intermediate', minutes: 9, calories: 120, description: 'Longer intervals to develop staying power.', exercises: <String>['Squat Jumps', 'Shadow Boxing', 'Fast Feet', 'Star Jumps', 'Jump Rope Mime', 'Step Touch', 'March In Place', 'Jumping Jacks', 'High Knees', 'Butt Kicks']),
  Workout(id: 'cardio-cardio-finisher', name: 'Cardio Finisher', category: 'Cardio', difficulty: 'Advanced', minutes: 6, calories: 90, description: 'A brutal short finisher to add to any workout.', exercises: <String>['Star Jumps', 'Jump Rope Mime', 'Step Touch', 'March In Place', 'Jumping Jacks', 'High Knees']),
  Workout(id: 'upper-body-upper-body-basics', name: 'Upper Body Basics', category: 'Upper Body', difficulty: 'Beginner', minutes: 5, calories: 61, description: 'Simple pushing and pulling for a stronger upper body.', exercises: <String>['Push Ups', 'Pike Push Ups', 'Tricep Dips', 'Superman', 'Band Pull Apart', 'Shoulder Press']),
  Workout(id: 'upper-body-push-pull-circuit', name: 'Push Pull Circuit', category: 'Upper Body', difficulty: 'Intermediate', minutes: 8, calories: 96, description: 'Alternate pushing and pulling to balance your training.', exercises: <String>['Superman', 'Band Pull Apart', 'Shoulder Press', 'Bicep Curls', 'Lateral Raise', 'Bent Over Row', 'Diamond Push Ups', 'Wide Push Ups']),
  Workout(id: 'upper-body-dumbbell-upper-body', name: 'Dumbbell Upper Body', category: 'Upper Body', difficulty: 'Intermediate', minutes: 7, calories: 84, description: 'A dumbbell-focused session for shoulders, back and arms.', exercises: <String>['Bicep Curls', 'Lateral Raise', 'Bent Over Row', 'Diamond Push Ups', 'Wide Push Ups', 'Arm Circles', 'Prone Y Raise']),
  Workout(id: 'upper-body-bodyweight-upper-strength', name: 'Bodyweight Upper Strength', category: 'Upper Body', difficulty: 'Intermediate', minutes: 7, calories: 84, description: 'No equipment needed â€” just you and the floor.', exercises: <String>['Diamond Push Ups', 'Wide Push Ups', 'Arm Circles', 'Prone Y Raise', 'Reverse Snow Angels', 'Knee Push Ups', 'Push Ups']),
  Workout(id: 'upper-body-shoulder-sculpt', name: 'Shoulder Sculpt', category: 'Upper Body', difficulty: 'Intermediate', minutes: 6, calories: 72, description: 'Targeted shoulder work for posture and definition.', exercises: <String>['Prone Y Raise', 'Reverse Snow Angels', 'Knee Push Ups', 'Push Ups', 'Pike Push Ups', 'Tricep Dips']),
  Workout(id: 'upper-body-upper-body-burnout', name: 'Upper Body Burnout', category: 'Upper Body', difficulty: 'Advanced', minutes: 11, calories: 135, description: 'High volume work to fully fatigue the upper body.', exercises: <String>['Push Ups', 'Pike Push Ups', 'Tricep Dips', 'Superman', 'Band Pull Apart', 'Shoulder Press', 'Bicep Curls', 'Lateral Raise', 'Bent Over Row']),
  Workout(id: 'upper-body-posture-builder', name: 'Posture Builder', category: 'Upper Body', difficulty: 'Beginner', minutes: 5, calories: 61, description: 'Back-focused work to counteract sitting all day.', exercises: <String>['Superman', 'Band Pull Apart', 'Shoulder Press', 'Bicep Curls', 'Lateral Raise', 'Bent Over Row']),
  Workout(id: 'upper-body-band-upper-body', name: 'Band Upper Body', category: 'Upper Body', difficulty: 'Beginner', minutes: 5, calories: 61, description: 'Resistance band training that\'s easy on the joints.', exercises: <String>['Bicep Curls', 'Lateral Raise', 'Bent Over Row', 'Diamond Push Ups', 'Wide Push Ups', 'Arm Circles']),
  Workout(id: 'upper-body-chest-and-triceps', name: 'Chest And Triceps', category: 'Upper Body', difficulty: 'Intermediate', minutes: 7, calories: 84, description: 'Press-focused session for chest and arm strength.', exercises: <String>['Diamond Push Ups', 'Wide Push Ups', 'Arm Circles', 'Prone Y Raise', 'Reverse Snow Angels', 'Knee Push Ups', 'Push Ups']),
  Workout(id: 'upper-body-back-and-biceps', name: 'Back And Biceps', category: 'Upper Body', difficulty: 'Intermediate', minutes: 7, calories: 84, description: 'Pull-focused session for a strong, healthy back.', exercises: <String>['Prone Y Raise', 'Reverse Snow Angels', 'Knee Push Ups', 'Push Ups', 'Pike Push Ups', 'Tricep Dips', 'Superman']),
  Workout(id: 'lower-body-leg-day-basics', name: 'Leg Day Basics', category: 'Lower Body', difficulty: 'Beginner', minutes: 5, calories: 61, description: 'Foundational leg strength without any equipment.', exercises: <String>['Lunges', 'Reverse Lunges', 'Glute Bridges', 'Wall Sit', 'Calf Raises', 'Sumo Squats']),
  Workout(id: 'lower-body-glute-focus', name: 'Glute Focus', category: 'Lower Body', difficulty: 'Intermediate', minutes: 7, calories: 84, description: 'Targeted glute work for strength and hip health.', exercises: <String>['Wall Sit', 'Calf Raises', 'Sumo Squats', 'Side Lunges', 'Curtsy Lunges', 'Single Leg Bridge', 'Donkey Kicks']),
  Workout(id: 'lower-body-lower-body-strength', name: 'Lower Body Strength', category: 'Lower Body', difficulty: 'Intermediate', minutes: 8, calories: 96, description: 'Heavier, slower work to build real leg strength.', exercises: <String>['Side Lunges', 'Curtsy Lunges', 'Single Leg Bridge', 'Donkey Kicks', 'Fire Hydrants', 'Squat Jumps', 'Goblet Squat', 'Romanian Deadlift']),
  Workout(id: 'lower-body-quad-burner', name: 'Quad Burner', category: 'Lower Body', difficulty: 'Advanced', minutes: 8, calories: 105, description: 'Squat-heavy session â€” expect your legs to talk back.', exercises: <String>['Donkey Kicks', 'Fire Hydrants', 'Squat Jumps', 'Goblet Squat', 'Romanian Deadlift', 'Band Lateral Walk', 'Step Ups']),
  Workout(id: 'lower-body-hamstrings-and-glutes', name: 'Hamstrings And Glutes', category: 'Lower Body', difficulty: 'Intermediate', minutes: 7, calories: 84, description: 'Hinge patterns for the back of your legs.', exercises: <String>['Goblet Squat', 'Romanian Deadlift', 'Band Lateral Walk', 'Step Ups', 'Bodyweight Squats', 'Lunges', 'Reverse Lunges']),
  Workout(id: 'lower-body-bodyweight-leg-circuit', name: 'Bodyweight Leg Circuit', category: 'Lower Body', difficulty: 'Beginner', minutes: 6, calories: 71, description: 'Continuous leg circuit you can do anywhere.', exercises: <String>['Step Ups', 'Bodyweight Squats', 'Lunges', 'Reverse Lunges', 'Glute Bridges', 'Wall Sit', 'Calf Raises']),
  Workout(id: 'lower-body-dumbbell-legs', name: 'Dumbbell Legs', category: 'Lower Body', difficulty: 'Advanced', minutes: 8, calories: 105, description: 'Add load for progressive lower body strength.', exercises: <String>['Reverse Lunges', 'Glute Bridges', 'Wall Sit', 'Calf Raises', 'Sumo Squats', 'Side Lunges', 'Curtsy Lunges']),
  Workout(id: 'lower-body-band-lower-body', name: 'Band Lower Body', category: 'Lower Body', difficulty: 'Beginner', minutes: 5, calories: 61, description: 'Band-based activation and strength for hips and glutes.', exercises: <String>['Calf Raises', 'Sumo Squats', 'Side Lunges', 'Curtsy Lunges', 'Single Leg Bridge', 'Donkey Kicks']),
  Workout(id: 'lower-body-single-leg-stability', name: 'Single Leg Stability', category: 'Lower Body', difficulty: 'Intermediate', minutes: 7, calories: 84, description: 'Balance-focused work to even out left and right.', exercises: <String>['Curtsy Lunges', 'Single Leg Bridge', 'Donkey Kicks', 'Fire Hydrants', 'Squat Jumps', 'Goblet Squat', 'Romanian Deadlift']),
  Workout(id: 'lower-body-legs-and-calves', name: 'Legs And Calves', category: 'Lower Body', difficulty: 'Intermediate', minutes: 8, calories: 96, description: 'Complete lower body session, calves included.', exercises: <String>['Fire Hydrants', 'Squat Jumps', 'Goblet Squat', 'Romanian Deadlift', 'Band Lateral Walk', 'Step Ups', 'Bodyweight Squats', 'Lunges']),
  Workout(id: 'abs-core-core-basics', name: 'Core Basics', category: 'Abs/Core', difficulty: 'Beginner', minutes: 4, calories: 51, description: 'Learn to brace properly before adding intensity.', exercises: <String>['Dead Bug', 'Bird Dog', 'Hollow Hold', 'Toe Touches', 'Plank Shoulder Taps']),
  Workout(id: 'abs-core-six-pack-circuit', name: 'Six Pack Circuit', category: 'Abs/Core', difficulty: 'Intermediate', minutes: 7, calories: 96, description: 'Classic ab circuit hitting upper, lower and obliques.', exercises: <String>['Toe Touches', 'Plank Shoulder Taps', 'Mountain Climbers', 'Plank', 'Crunches', 'Bicycle Crunches', 'Leg Raises', 'Russian Twists']),
  Workout(id: 'abs-core-plank-challenge', name: 'Plank Challenge', category: 'Abs/Core', difficulty: 'Intermediate', minutes: 5, calories: 72, description: 'Isometric holds to build deep core endurance.', exercises: <String>['Plank', 'Crunches', 'Bicycle Crunches', 'Leg Raises', 'Russian Twists', 'Flutter Kicks']),
  Workout(id: 'abs-core-oblique-focus', name: 'Oblique Focus', category: 'Abs/Core', difficulty: 'Intermediate', minutes: 5, calories: 72, description: 'Rotation and side work for the waist.', exercises: <String>['Leg Raises', 'Russian Twists', 'Flutter Kicks', 'Side Plank', 'Dead Bug', 'Bird Dog']),
  Workout(id: 'abs-core-lower-ab-focus', name: 'Lower Ab Focus', category: 'Abs/Core', difficulty: 'Intermediate', minutes: 5, calories: 72, description: 'Target the lower abs with leg-driven movements.', exercises: <String>['Side Plank', 'Dead Bug', 'Bird Dog', 'Hollow Hold', 'Toe Touches', 'Plank Shoulder Taps']),
  Workout(id: 'abs-core-core-power', name: 'Core Power', category: 'Abs/Core', difficulty: 'Advanced', minutes: 9, calories: 135, description: 'Demanding core session for experienced trainees.', exercises: <String>['Hollow Hold', 'Toe Touches', 'Plank Shoulder Taps', 'Mountain Climbers', 'Plank', 'Crunches', 'Bicycle Crunches', 'Leg Raises', 'Russian Twists']),
  Workout(id: 'abs-core-5-minute-abs', name: '5 Minute Abs', category: 'Abs/Core', difficulty: 'Beginner', minutes: 4, calories: 51, description: 'Quick daily core hit you can fit in anywhere.', exercises: <String>['Mountain Climbers', 'Plank', 'Crunches', 'Bicycle Crunches', 'Leg Raises']),
  Workout(id: 'abs-core-standing-core', name: 'Standing Core', category: 'Abs/Core', difficulty: 'Beginner', minutes: 5, calories: 61, description: 'No floor needed â€” core work on your feet.', exercises: <String>['Bicycle Crunches', 'Leg Raises', 'Russian Twists', 'Flutter Kicks', 'Side Plank', 'Dead Bug']),
  Workout(id: 'abs-core-core-stability', name: 'Core Stability', category: 'Abs/Core', difficulty: 'Beginner', minutes: 5, calories: 61, description: 'Slow controlled work for a resilient back and core.', exercises: <String>['Flutter Kicks', 'Side Plank', 'Dead Bug', 'Bird Dog', 'Hollow Hold', 'Toe Touches']),
  Workout(id: 'abs-core-ab-finisher', name: 'Ab Finisher', category: 'Abs/Core', difficulty: 'Advanced', minutes: 7, calories: 105, description: 'Add this to the end of any workout for extra burn.', exercises: <String>['Bird Dog', 'Hollow Hold', 'Toe Touches', 'Plank Shoulder Taps', 'Mountain Climbers', 'Plank', 'Crunches']),
  Workout(id: 'stretching-morning-mobility', name: 'Morning Mobility', category: 'Stretching', difficulty: 'Beginner', minutes: 4, calories: 61, description: 'Wake your joints up with slow, easy movement.', exercises: <String>['Shoulder Rolls', 'Arm Circles', 'Cat Cow', 'Childs Pose', 'Hamstring Stretch', 'Quad Stretch']),
  Workout(id: 'stretching-full-body-stretch', name: 'Full Body Stretch', category: 'Stretching', difficulty: 'Beginner', minutes: 5, calories: 82, description: 'Head-to-toe stretching for general flexibility.', exercises: <String>['Childs Pose', 'Hamstring Stretch', 'Quad Stretch', 'Hip Flexor Stretch', 'Chest Opener', 'Neck Release', 'Seated Twist', 'Figure Four']),
  Workout(id: 'stretching-post-workout-cooldown', name: 'Post Workout Cooldown', category: 'Stretching', difficulty: 'Beginner', minutes: 4, calories: 61, description: 'Bring the heart rate down and stretch what you trained.', exercises: <String>['Hip Flexor Stretch', 'Chest Opener', 'Neck Release', 'Seated Twist', 'Figure Four', 'Downward Dog']),
  Workout(id: 'stretching-lower-body-stretch', name: 'Lower Body Stretch', category: 'Stretching', difficulty: 'Beginner', minutes: 4, calories: 61, description: 'Hips, hamstrings and quads get some attention.', exercises: <String>['Seated Twist', 'Figure Four', 'Downward Dog', 'World Greatest Stretch', 'Ankle Circles', 'Shoulder Rolls']),
  Workout(id: 'stretching-upper-body-stretch', name: 'Upper Body Stretch', category: 'Stretching', difficulty: 'Beginner', minutes: 4, calories: 61, description: 'Open the chest and release the shoulders and neck.', exercises: <String>['World Greatest Stretch', 'Ankle Circles', 'Shoulder Rolls', 'Arm Circles', 'Cat Cow', 'Childs Pose']),
  Workout(id: 'stretching-hip-opener-flow', name: 'Hip Opener Flow', category: 'Stretching', difficulty: 'Beginner', minutes: 4, calories: 61, description: 'Relieve tight hips from long hours of sitting.', exercises: <String>['Arm Circles', 'Cat Cow', 'Childs Pose', 'Hamstring Stretch', 'Quad Stretch', 'Hip Flexor Stretch']),
  Workout(id: 'stretching-back-relief', name: 'Back Relief', category: 'Stretching', difficulty: 'Beginner', minutes: 4, calories: 61, description: 'Gentle spinal movement to ease a stiff back.', exercises: <String>['Hamstring Stretch', 'Quad Stretch', 'Hip Flexor Stretch', 'Chest Opener', 'Neck Release', 'Seated Twist']),
  Workout(id: 'stretching-bedtime-wind-down', name: 'Bedtime Wind Down', category: 'Stretching', difficulty: 'Beginner', minutes: 4, calories: 61, description: 'Slow, calming stretches to finish the day.', exercises: <String>['Chest Opener', 'Neck Release', 'Seated Twist', 'Figure Four', 'Downward Dog', 'World Greatest Stretch']),
  Workout(id: 'stretching-desk-worker-reset', name: 'Desk Worker Reset', category: 'Stretching', difficulty: 'Beginner', minutes: 4, calories: 61, description: 'Undo the effects of sitting in a chair all day.', exercises: <String>['Figure Four', 'Downward Dog', 'World Greatest Stretch', 'Ankle Circles', 'Shoulder Rolls', 'Arm Circles']),
  Workout(id: 'stretching-deep-flexibility', name: 'Deep Flexibility', category: 'Stretching', difficulty: 'Intermediate', minutes: 7, calories: 108, description: 'Longer holds for real flexibility gains over time.', exercises: <String>['Ankle Circles', 'Shoulder Rolls', 'Arm Circles', 'Cat Cow', 'Childs Pose', 'Hamstring Stretch', 'Quad Stretch', 'Hip Flexor Stretch', 'Chest Opener']),
  Workout(id: 'chest-chest-builder', name: 'Chest Builder', category: 'Chest', difficulty: 'Intermediate', minutes: 6, calories: 72, description: 'Classic pressing volume for chest development.', exercises: <String>['Incline Push Ups', 'Knee Push Ups', 'Chest Press', 'Chest Fly', 'Band Chest Press', 'Diamond Push Ups']),
  Workout(id: 'chest-push-up-ladder', name: 'Push Up Ladder', category: 'Chest', difficulty: 'Advanced', minutes: 7, calories: 90, description: 'Every push up variation, back to back.', exercises: <String>['Chest Fly', 'Band Chest Press', 'Diamond Push Ups', 'Push Ups', 'Wide Push Ups', 'Incline Push Ups']),
  Workout(id: 'chest-dumbbell-chest', name: 'Dumbbell Chest', category: 'Chest', difficulty: 'Intermediate', minutes: 5, calories: 60, description: 'Press and fly work with a pair of dumbbells.', exercises: <String>['Push Ups', 'Wide Push Ups', 'Incline Push Ups', 'Knee Push Ups', 'Chest Press']),
  Workout(id: 'chest-beginner-chest', name: 'Beginner Chest', category: 'Chest', difficulty: 'Beginner', minutes: 4, calories: 51, description: 'Scaled pressing to build your first push ups.', exercises: <String>['Knee Push Ups', 'Chest Press', 'Chest Fly', 'Band Chest Press', 'Diamond Push Ups']),
  Workout(id: 'back-strong-back', name: 'Strong Back', category: 'Back', difficulty: 'Intermediate', minutes: 6, calories: 72, description: 'Rowing and extension work for a resilient back.', exercises: <String>['Prone Y Raise', 'Bird Dog', 'Superman', 'Reverse Snow Angels', 'Bent Over Row', 'Single Arm Row']),
  Workout(id: 'back-back-without-equipment', name: 'Back Without Equipment', category: 'Back', difficulty: 'Beginner', minutes: 4, calories: 51, description: 'Floor-based back work, no gear required.', exercises: <String>['Reverse Snow Angels', 'Bent Over Row', 'Single Arm Row', 'Band Pull Apart', 'Band Row']),
  Workout(id: 'back-band-back-session', name: 'Band Back Session', category: 'Back', difficulty: 'Beginner', minutes: 4, calories: 51, description: 'Resistance band pulls for posture and strength.', exercises: <String>['Band Pull Apart', 'Band Row', 'Prone Y Raise', 'Bird Dog', 'Superman']),
  Workout(id: 'back-back-strength-builder', name: 'Back Strength Builder', category: 'Back', difficulty: 'Advanced', minutes: 8, calories: 105, description: 'Higher volume pulling for serious back development.', exercises: <String>['Bird Dog', 'Superman', 'Reverse Snow Angels', 'Bent Over Row', 'Single Arm Row', 'Band Pull Apart', 'Band Row']),
  Workout(id: 'arms-arm-sculpt', name: 'Arm Sculpt', category: 'Arms', difficulty: 'Intermediate', minutes: 6, calories: 72, description: 'Biceps and triceps in a straightforward superset format.', exercises: <String>['Tricep Kickback', 'Diamond Push Ups', 'Shoulder Press', 'Lateral Raise', 'Band Bicep Curl', 'Arm Circles']),
  Workout(id: 'arms-bodyweight-arms', name: 'Bodyweight Arms', category: 'Arms', difficulty: 'Beginner', minutes: 4, calories: 51, description: 'Arm training with nothing but your bodyweight.', exercises: <String>['Lateral Raise', 'Band Bicep Curl', 'Arm Circles', 'Bicep Curls', 'Tricep Dips']),
  Workout(id: 'arms-dumbbell-arms', name: 'Dumbbell Arms', category: 'Arms', difficulty: 'Intermediate', minutes: 6, calories: 72, description: 'Curls, presses and extensions with dumbbells.', exercises: <String>['Bicep Curls', 'Tricep Dips', 'Tricep Kickback', 'Diamond Push Ups', 'Shoulder Press', 'Lateral Raise']),
  Workout(id: 'arms-arm-burnout', name: 'Arm Burnout', category: 'Arms', difficulty: 'Advanced', minutes: 8, calories: 105, description: 'High rep finisher for a serious pump.', exercises: <String>['Diamond Push Ups', 'Shoulder Press', 'Lateral Raise', 'Band Bicep Curl', 'Arm Circles', 'Bicep Curls', 'Tricep Dips']),
  Workout(id: 'legs-squat-focus', name: 'Squat Focus', category: 'Legs', difficulty: 'Intermediate', minutes: 6, calories: 72, description: 'All squats, all the time. Build serious leg strength.', exercises: <String>['Side Lunges', 'Wall Sit', 'Calf Raises', 'Squat Jumps', 'Goblet Squat', 'Step Ups']),
  Workout(id: 'legs-lunge-matrix', name: 'Lunge Matrix', category: 'Legs', difficulty: 'Intermediate', minutes: 6, calories: 72, description: 'Lunges in every direction for balanced legs.', exercises: <String>['Squat Jumps', 'Goblet Squat', 'Step Ups', 'Bodyweight Squats', 'Sumo Squats', 'Lunges']),
  Workout(id: 'legs-explosive-legs', name: 'Explosive Legs', category: 'Legs', difficulty: 'Advanced', minutes: 7, calories: 90, description: 'Jump training for power and athleticism.', exercises: <String>['Bodyweight Squats', 'Sumo Squats', 'Lunges', 'Side Lunges', 'Wall Sit', 'Calf Raises']),
  Workout(id: 'legs-easy-legs', name: 'Easy Legs', category: 'Legs', difficulty: 'Beginner', minutes: 4, calories: 51, description: 'Low impact leg work suitable for any level.', exercises: <String>['Side Lunges', 'Wall Sit', 'Calf Raises', 'Squat Jumps', 'Goblet Squat']),
  Workout(id: 'home-workout-living-room-workout', name: 'Living Room Workout', category: 'Home Workout', difficulty: 'Beginner', minutes: 5, calories: 61, description: 'Fits in a small space with zero equipment.', exercises: <String>['Crunches', 'Wall Sit', 'Superman', 'Reverse Lunges', 'March In Place', 'Calf Raises']),
  Workout(id: 'home-workout-quiet-apartment-session', name: 'Quiet Apartment Session', category: 'Home Workout', difficulty: 'Beginner', minutes: 5, calories: 61, description: 'No jumping and no noise â€” neighbour friendly.', exercises: <String>['Reverse Lunges', 'March In Place', 'Calf Raises', 'Bodyweight Squats', 'Knee Push Ups', 'Glute Bridges']),
  Workout(id: 'home-workout-home-strength-circuit', name: 'Home Strength Circuit', category: 'Home Workout', difficulty: 'Intermediate', minutes: 8, calories: 96, description: 'A full strength session in your own home.', exercises: <String>['Bodyweight Squats', 'Knee Push Ups', 'Glute Bridges', 'Plank', 'Step Touch', 'Crunches', 'Wall Sit', 'Superman']),
  Workout(id: 'home-workout-hotel-room-workout', name: 'Hotel Room Workout', category: 'Home Workout', difficulty: 'Beginner', minutes: 5, calories: 61, description: 'Travel-friendly training in a tiny space.', exercises: <String>['Plank', 'Step Touch', 'Crunches', 'Wall Sit', 'Superman', 'Reverse Lunges']),
  Workout(id: 'home-workout-family-friendly-moves', name: 'Family Friendly Moves', category: 'Home Workout', difficulty: 'Beginner', minutes: 5, calories: 61, description: 'Simple exercises the whole household can join in on.', exercises: <String>['Wall Sit', 'Superman', 'Reverse Lunges', 'March In Place', 'Calf Raises', 'Bodyweight Squats']),
  Workout(id: 'no-equipment-zero-equipment-blast', name: 'Zero Equipment Blast', category: 'No Equipment', difficulty: 'Intermediate', minutes: 8, calories: 96, description: 'Nothing but your bodyweight and some determination.', exercises: <String>['Wall Sit', 'Squat Jumps', 'Jumping Jacks', 'Bodyweight Squats', 'Push Ups', 'Lunges', 'Plank', 'Burpees']),
  Workout(id: 'no-equipment-anywhere-anytime', name: 'Anywhere Anytime', category: 'No Equipment', difficulty: 'Beginner', minutes: 5, calories: 61, description: 'A workout that travels with you everywhere.', exercises: <String>['Bodyweight Squats', 'Push Ups', 'Lunges', 'Plank', 'Burpees', 'Mountain Climbers']),
  Workout(id: 'no-equipment-park-workout', name: 'Park Workout', category: 'No Equipment', difficulty: 'Intermediate', minutes: 7, calories: 84, description: 'Take your training outdoors.', exercises: <String>['Plank', 'Burpees', 'Mountain Climbers', 'High Knees', 'Crunches', 'Wall Sit', 'Squat Jumps']),
  Workout(id: 'no-equipment-no-excuses-circuit', name: 'No Excuses Circuit', category: 'No Equipment', difficulty: 'Advanced', minutes: 10, calories: 135, description: 'When motivation is low, this one still gets done.', exercises: <String>['High Knees', 'Crunches', 'Wall Sit', 'Squat Jumps', 'Jumping Jacks', 'Bodyweight Squats', 'Push Ups', 'Lunges', 'Plank']),
  Workout(id: 'no-equipment-10-minute-no-gear', name: '10 Minute No Gear', category: 'No Equipment', difficulty: 'Beginner', minutes: 4, calories: 51, description: 'Ten focused minutes, no equipment required.', exercises: <String>['Squat Jumps', 'Jumping Jacks', 'Bodyweight Squats', 'Push Ups', 'Lunges']),
];


// Full education articles imported from the Lovable source.
final nutritionArticles = <NutritionArticle>[
  NutritionArticle(icon: '🥩', title: 'Protein', summary: 'The building block your body uses to repair and maintain muscle.', details: 'Protein provides amino acids, which your body uses to repair tissue after training and to maintain muscle over time. Most general guidance suggests spreading protein across your meals rather than eating it all in one sitting.', benefits: <String>['Supports muscle repair after training', 'Tends to be filling, which can help with appetite management', 'Contributes to maintaining muscle while losing weight'], examples: <String>['Chicken and turkey', 'Fish and seafood', 'Eggs', 'Greek yoghurt', 'Lentils and beans', 'Tofu and tempeh'], tips: <String>['Aim to include a protein source in each main meal.', 'Plant proteins work well when you combine a variety across the day.', 'Protein powder is a convenience option, not a requirement.']),
  NutritionArticle(icon: '🍚', title: 'Carbohydrates', summary: 'Your body\'s most accessible fuel source for training.', details: 'Carbohydrates are broken down into glucose, which fuels higher-intensity exercise. Minimally processed sources also bring fibre, vitamins and minerals along with the energy.', benefits: <String>['Provides readily available energy for workouts', 'Fibre-rich sources support digestive health', 'Helps replenish energy stores after exercise'], examples: <String>['Oats', 'Brown rice', 'Potatoes and sweet potatoes', 'Wholegrain bread and pasta', 'Fruit', 'Beans'], tips: <String>['Favour wholegrain and minimally processed options most of the time.', 'Carbs before training can help you feel stronger during the session.', 'You don\'t need to fear carbohydrates to lose weight â€” total intake matters more.']),
  NutritionArticle(icon: '🥑', title: 'Healthy Fats', summary: 'Essential for hormones, brain health and nutrient absorption.', details: 'Fats are energy dense and essential. Unsaturated fats from foods like nuts, seeds, olive oil and oily fish are generally emphasised in dietary guidelines over heavily processed and saturated fat sources.', benefits: <String>['Helps your body absorb vitamins A, D, E and K', 'Supports normal hormone production', 'Adds flavour and satisfaction to meals'], examples: <String>['Olive oil', 'Avocado', 'Almonds and walnuts', 'Chia and flax seeds', 'Salmon and sardines'], tips: <String>['Measure oils and nut butters â€” calories add up quickly.', 'Include an oily fish source a couple of times a week if you eat fish.', 'Nuts make a simple, portable snack.']),
  NutritionArticle(icon: '🍎', title: 'Fruits', summary: 'Naturally sweet, hydrating and full of fibre and vitamins.', details: 'Fruit provides vitamins, minerals, fibre and water in a convenient package. Variety matters: different colours tend to bring different nutrients.', benefits: <String>['Supports fibre intake', 'Contributes to daily hydration', 'Convenient alternative to sugary snacks'], examples: <String>['Berries', 'Bananas', 'Apples and pears', 'Oranges', 'Kiwi', 'Frozen mixed fruit'], tips: <String>['Frozen fruit is just as useful as fresh and often cheaper.', 'Whole fruit is generally more filling than juice.', 'Pair fruit with protein or fat for a more satisfying snack.']),
  NutritionArticle(icon: '🥦', title: 'Vegetables', summary: 'High volume, low calorie, and packed with micronutrients.', details: 'Vegetables add nutrients and bulk to meals for very few calories, which can make eating in a calorie deficit far more comfortable.', benefits: <String>['Adds volume to meals without many calories', 'Broad range of vitamins and minerals', 'Supports fibre and gut health'], examples: <String>['Broccoli', 'Spinach and leafy greens', 'Peppers', 'Carrots', 'Courgette', 'Tomatoes'], tips: <String>['Roasting with a little oil and spice makes vegetables far more appealing.', 'Keep bagged frozen vegetables on hand for busy days.', 'Try to fill roughly half your plate with vegetables at main meals.']),
  NutritionArticle(icon: '💧', title: 'Hydration', summary: 'Water affects energy, focus and how you feel while training.', details: 'Even mild dehydration can make training feel harder. Needs vary with body size, climate and activity, so use thirst and urine colour as practical everyday cues.', benefits: <String>['Supports temperature regulation during exercise', 'Helps maintain focus and energy', 'Aids normal digestion'], examples: <String>['Plain water', 'Sparkling water', 'Herbal tea', 'Water-rich fruit like watermelon', 'Milk'], tips: <String>['Keep a bottle within arm\'s reach â€” visibility drives habit.', 'Drink a glass with every meal as an easy anchor.', 'Increase intake in hot weather and around longer workouts.']),
  NutritionArticle(icon: '⚡', title: 'Pre-Workout Nutrition', summary: 'Fuel that helps you train with more energy and comfort.', details: 'A meal with carbohydrates and some protein 1-3 hours before training suits most people. Closer to the session, smaller and lower-fibre snacks tend to sit better.', benefits: <String>['Can improve energy during the session', 'Reduces the chance of feeling light-headed', 'Helps you maintain intensity'], examples: <String>['Banana with peanut butter', 'Oats with yoghurt', 'Toast with honey', 'Rice cakes', 'A small smoothie'], tips: <String>['Experiment to find what your stomach tolerates.', 'Very high fat or high fibre meals right before training can cause discomfort.', 'Short easy sessions may not need any food beforehand.']),
  NutritionArticle(icon: '🥛', title: 'Post-Workout Nutrition', summary: 'Refuel and give your body what it needs to recover.', details: 'After training, a meal containing protein and carbohydrates supports recovery. The old 30-minute \'anabolic window\' idea is now considered much less strict â€” total daily intake matters more.', benefits: <String>['Supports muscle repair', 'Replenishes energy stores', 'Helps you feel recovered for the next session'], examples: <String>['Chicken with rice and vegetables', 'Greek yoghurt with fruit', 'Eggs on wholegrain toast', 'Tofu stir fry', 'Milk-based smoothie'], tips: <String>['Rehydrate as well as refuel.', 'A normal balanced meal works fine â€” shakes are optional.', 'Sleep is one of the most powerful recovery tools you have.']),
  NutritionArticle(icon: '🥕', title: 'Healthy Snacks', summary: 'Bridge the gap between meals without derailing your goals.', details: 'Snacks that combine protein or fat with fibre tend to keep you satisfied longer than refined carbohydrates alone. Portioning ahead of time helps.', benefits: <String>['Steadier energy between meals', 'Can reduce overeating at dinner', 'Extra chance to hit protein and fibre targets'], examples: <String>['Greek yoghurt with berries', 'Apple with nut butter', 'Hummus and carrot sticks', 'Boiled eggs', 'A small handful of nuts', 'Cottage cheese'], tips: <String>['Pre-portion snacks instead of eating from the bag.', 'Keep a default option ready so you\'re not deciding while hungry.', 'If you\'re constantly hungry, your main meals may be too small.']),
];


// Original Lovable CDN assets, retained per-workout.
const workoutImageUrls = <String, String>{
  'beginner-first-steps': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/cc721f49-09b6-4a28-b955-fd2f940c3026/beginner-first-steps.jpg',
  'beginner-beginner-full-body': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/7889b7da-697e-4150-a637-2b69d7e0ca0f/beginner-beginner-full-body.jpg',
  'beginner-easy-morning-wake-up': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/977f1684-d126-44c0-99fc-affb839a2bc9/beginner-easy-morning-wake-up.jpg',
  'beginner-gentle-strength-start': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/713f5867-ce6a-45b9-b2de-d0dc94d64c1a/beginner-gentle-strength-start.jpg',
  'beginner-beginner-core-basics': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/022f8824-1fd6-469e-b4e5-373ddca8d4b9/beginner-beginner-core-basics.jpg',
  'beginner-low-impact-starter': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/f10857cf-5403-40af-87de-fa6f2c110e23/beginner-low-impact-starter.jpg',
  'beginner-confidence-builder': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/c1d4bd75-bcf1-4e87-b5cf-1faeeed31615/beginner-confidence-builder.jpg',
  'beginner-beginner-strength-circuit': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/069ba60a-8f3b-4c58-a704-6c097bb6f945/beginner-beginner-strength-circuit.jpg',
  'beginner-desk-break-reset': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/15d368bb-65dc-4a12-96c8-fd6c7874fc90/beginner-desk-break-reset.jpg',
  'beginner-beginner-progression': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/30f29ef9-9842-4476-96e2-7a3b88d52c10/beginner-beginner-progression.jpg',
  'full-body-total-body-blast': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/2bcb1674-f87d-4794-b8ff-44985922ab74/full-body-total-body-blast.jpg',
  'full-body-full-body-foundations': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/099e771e-e08c-4131-8f29-f1b195a931a9/full-body-full-body-foundations.jpg',
  'full-body-metabolic-full-body': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/01673935-6c2e-4743-828c-423163a0a8d5/full-body-metabolic-full-body.jpg',
  'full-body-30-minute-full-body': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/8cccd37b-f526-433a-b9a3-d8c3a8db7f25/full-body-30-minute-full-body.jpg',
  'full-body-full-body-power': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/480c5ae2-76d1-415a-815a-699648e397ad/full-body-full-body-power.jpg',
  'full-body-express-full-body': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/5bbb28a2-543c-44d0-bcc4-ec5a6acc18f4/full-body-express-full-body.jpg',
  'full-body-strength-endurance-mix': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/743198fe-907b-4882-a87a-7a755157ef08/full-body-strength-endurance-mix.jpg',
  'full-body-full-body-burn': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/5a429b1a-fb6e-40e0-8376-f5ba28ed4722/full-body-full-body-burn.jpg',
  'full-body-balanced-body-circuit': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/0919ed8e-d213-4ab4-8e4b-97060b948907/full-body-balanced-body-circuit.jpg',
  'full-body-weekend-warrior': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/abd6dc07-5bb9-4ae1-bdb1-c43f2fc55f61/full-body-weekend-warrior.jpg',
  'cardio-cardio-kickstart': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/abda4f69-8b2b-4a17-ac27-945349e4914c/cardio-cardio-kickstart.jpg',
  'cardio-hiit-express': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/1c3376d2-98ab-4db0-805f-99a4de1585ef/cardio-hiit-express.jpg',
  'cardio-fat-burn-circuit': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/a4b6836e-f489-4b33-8674-fcc439bb4d34/cardio-fat-burn-circuit.jpg',
  'cardio-low-impact-cardio': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/77d6e6b0-7755-4cca-a88d-57aed9961b94/cardio-low-impact-cardio.jpg',
  'cardio-boxing-conditioning': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/945877c4-5ed8-4f3e-8629-8e02e20f806a/cardio-boxing-conditioning.jpg',
  'cardio-sprint-intervals': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/c94f9996-f14e-46e3-bdb0-1a74cd4ba67f/cardio-sprint-intervals.jpg',
  'cardio-cardio-core-combo': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/13fa1257-79d6-4062-af2e-8515acc686fa/cardio-cardio-core-combo.jpg',
  'cardio-morning-heart-starter': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/9a1c0a17-ff20-4a23-8e23-cf16b250345e/cardio-morning-heart-starter.jpg',
  'cardio-endurance-builder': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/cc378310-d6c4-4fa9-801f-3d6f8909b3a0/cardio-endurance-builder.jpg',
  'cardio-cardio-finisher': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/ca68a8cd-f968-4af8-ba15-0ba759121220/cardio-cardio-finisher.jpg',
  'upper-body-upper-body-basics': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/351fc160-8cd2-48a3-afca-56c5b0939c1d/upper-body-upper-body-basics.jpg',
  'upper-body-push-pull-circuit': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/f2dc862c-61ca-4089-bcbc-301a9634c89e/upper-body-push-pull-circuit.jpg',
  'upper-body-dumbbell-upper-body': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/5624fe0b-2a95-4445-8e28-274d6b3b9efb/upper-body-dumbbell-upper-body.jpg',
  'upper-body-bodyweight-upper-strength': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/5b54bf05-e405-45cc-9c97-b528c5f85866/upper-body-bodyweight-upper-strength.jpg',
  'upper-body-shoulder-sculpt': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/efa34bc3-1d0a-4736-8cf6-72176aeb85f9/upper-body-shoulder-sculpt.jpg',
  'upper-body-upper-body-burnout': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/8b70bb4d-ec72-46e1-8dea-13d9c0f5c7e6/upper-body-upper-body-burnout.jpg',
  'upper-body-posture-builder': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/57298b0d-a0c2-437b-82e8-f9e26c65cb96/upper-body-posture-builder.jpg',
  'upper-body-band-upper-body': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/ad3af34e-cb0a-4e7e-bc6e-468989478cb2/upper-body-band-upper-body.jpg',
  'upper-body-chest-and-triceps': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/8757d943-da21-499e-96ef-515fb472d766/upper-body-chest-and-triceps.jpg',
  'upper-body-back-and-biceps': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/25608366-18cd-4db7-ac76-a20911bd66ac/upper-body-back-and-biceps.jpg',
  'lower-body-leg-day-basics': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/2d37ec5d-c44c-45de-bd0f-252fa73d8697/lower-body-leg-day-basics.jpg',
  'lower-body-glute-focus': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/94b2dae1-76f1-4c61-8cee-e69cd8636f78/lower-body-glute-focus.jpg',
  'lower-body-lower-body-strength': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/dbd216eb-1dac-46ca-a45b-3acb0af36f50/lower-body-lower-body-strength.jpg',
  'lower-body-quad-burner': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/d04cc184-fbf9-405d-89fe-529c6677d286/lower-body-quad-burner.jpg',
  'lower-body-hamstrings-and-glutes': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/5abc9f33-225d-49ff-842f-114f58841452/lower-body-hamstrings-and-glutes.jpg',
  'lower-body-bodyweight-leg-circuit': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/4de48d71-4541-43d9-9823-dbd4469b5ccd/lower-body-bodyweight-leg-circuit.jpg',
  'lower-body-dumbbell-legs': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/ac1cd1a1-c93a-48f9-ae70-07b11d718d5e/lower-body-dumbbell-legs.jpg',
  'lower-body-band-lower-body': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/d5fc3fd9-a306-4d29-ba6e-ca81e059b8dd/lower-body-band-lower-body.jpg',
  'lower-body-single-leg-stability': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/4c11286c-f17f-40ca-a214-bba08b9dcea9/lower-body-single-leg-stability.jpg',
  'lower-body-legs-and-calves': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/63b6aeb7-5e76-4bdc-9191-00490a02354a/lower-body-legs-and-calves.jpg',
  'abs-core-core-basics': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/c5cc8980-8cb5-4d5d-a7e6-b941e4f9867d/abs-core-core-basics.jpg',
  'abs-core-six-pack-circuit': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/8cb1f53b-d274-4c78-9557-72f2953b3caa/abs-core-six-pack-circuit.jpg',
  'abs-core-plank-challenge': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/62e898ba-ca75-4d5d-841f-73cd284fa2e1/abs-core-plank-challenge.jpg',
  'abs-core-oblique-focus': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/d2aac36f-e546-4cdd-958f-4b14e593e4db/abs-core-oblique-focus.jpg',
  'abs-core-lower-ab-focus': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/d9a3fa8b-b20b-4235-9d64-6d0149660be5/abs-core-lower-ab-focus.jpg',
  'abs-core-core-power': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/d323a9a5-4254-49fd-8569-ff1c53d9a32a/abs-core-core-power.jpg',
  'abs-core-5-minute-abs': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/755132ae-cca1-428c-859e-1ddb86c32ff3/abs-core-5-minute-abs.jpg',
  'abs-core-standing-core': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/6b96c800-b94b-4418-b226-e72d417ff9a2/abs-core-standing-core.jpg',
  'abs-core-core-stability': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/dbdf18b6-7235-4765-b0ca-18df5c6b29c7/abs-core-core-stability.jpg',
  'abs-core-ab-finisher': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/86b7f558-aef6-479e-96a9-5093a0aba0cc/abs-core-ab-finisher.jpg',
  'stretching-morning-mobility': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/d5769722-a1a2-4550-bdb1-00ce9b73eae6/stretching-morning-mobility.jpg',
  'stretching-full-body-stretch': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/9984abeb-127c-4f85-95bd-5666d85c2090/stretching-full-body-stretch.jpg',
  'stretching-post-workout-cooldown': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/9d813c12-9d8e-4d50-9578-0a3a5634f7b3/stretching-post-workout-cooldown.jpg',
  'stretching-lower-body-stretch': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/46767c14-b4c4-4c99-b88d-0b19c2263ae7/stretching-lower-body-stretch.jpg',
  'stretching-upper-body-stretch': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/87bb6fe6-cd7f-43aa-8aa7-e7ed269abf0a/stretching-upper-body-stretch.jpg',
  'stretching-hip-opener-flow': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/fef76066-5b37-422b-9721-1701c4e99d37/stretching-hip-opener-flow.jpg',
  'stretching-back-relief': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/d1a0fe90-1e5f-4ffc-aec8-22ee9623b320/stretching-back-relief.jpg',
  'stretching-bedtime-wind-down': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/bba291a1-d9c2-426c-8029-ec98ee0297b8/stretching-bedtime-wind-down.jpg',
  'stretching-desk-worker-reset': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/05c168b7-ac6a-4d66-a033-9951aac75f30/stretching-desk-worker-reset.jpg',
  'stretching-deep-flexibility': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/5593e7b4-0aa3-4363-8179-9667e517e017/stretching-deep-flexibility.jpg',
  'chest-chest-builder': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/16734e3e-9ec7-4774-9a8e-14d575d0ea66/chest-chest-builder.jpg',
  'chest-push-up-ladder': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/681a61dc-de5c-47f0-a8bb-ab955e167b5e/chest-push-up-ladder.jpg',
  'chest-dumbbell-chest': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/4bfaabea-2797-4ee9-869b-4177d57b8466/chest-dumbbell-chest.jpg',
  'chest-beginner-chest': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/3577da98-c404-4f4c-bc7f-552eee7cd7c6/chest-beginner-chest.jpg',
  'back-strong-back': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/f4981e1b-6d00-4f30-9653-59842ed5c323/back-strong-back.jpg',
  'back-back-without-equipment': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/283ede2f-3ddd-4321-ab66-ad48ff7e3398/back-back-without-equipment.jpg',
  'back-band-back-session': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/4c8a71ac-7d56-4717-b526-d9c1bb36197f/back-band-back-session.jpg',
  'back-back-strength-builder': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/b37c5f97-4a16-4f48-8d7b-08c7a8240a31/back-back-strength-builder.jpg',
  'arms-arm-sculpt': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/7a04804f-8632-426b-96f2-05f678178093/arms-arm-sculpt.jpg',
  'arms-bodyweight-arms': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/d9bf3e70-ad04-4c1d-abb6-d734e32c1795/arms-bodyweight-arms.jpg',
  'arms-dumbbell-arms': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/92d9ab48-8801-439d-8a1e-7bb97f9a0fee/arms-dumbbell-arms.jpg',
  'arms-arm-burnout': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/99529884-1e69-4d8f-8b40-cda23bcfcb9a/arms-arm-burnout.jpg',
  'legs-squat-focus': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/134fbb74-6ec4-47ca-8484-0b6fec62c830/legs-squat-focus.jpg',
  'legs-lunge-matrix': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/b361bef4-d263-4dfe-96e2-8f98bca7bf8d/legs-lunge-matrix.jpg',
  'legs-explosive-legs': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/a6ff64a7-2a97-46e1-af4c-e303a96c4760/legs-explosive-legs.jpg',
  'legs-easy-legs': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/100ea364-e6b6-482f-9bff-c613b4c71243/legs-easy-legs.jpg',
  'home-workout-living-room-workout': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/ad7d47ae-9e10-41a8-914e-75f8b1b2a581/home-workout-living-room-workout.jpg',
  'home-workout-quiet-apartment-session': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/3789a8db-e378-4257-9237-59d571f589db/home-workout-quiet-apartment-session.jpg',
  'home-workout-home-strength-circuit': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/308fc294-9f9d-4db3-9242-560f8a110b69/home-workout-home-strength-circuit.jpg',
  'home-workout-hotel-room-workout': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/66812f65-0341-4624-ab50-cd95b9c98f9f/home-workout-hotel-room-workout.jpg',
  'home-workout-family-friendly-moves': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/df8bcc13-8101-4408-a419-386e47383639/home-workout-family-friendly-moves.jpg',
  'no-equipment-zero-equipment-blast': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/66735ef6-ed38-49db-b158-49335344d29d/no-equipment-zero-equipment-blast.jpg',
  'no-equipment-anywhere-anytime': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/61011577-e888-46af-9f5c-dc98c331055c/no-equipment-anywhere-anytime.jpg',
  'no-equipment-park-workout': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/927b7346-cd4f-409c-b713-4810ca7b30b3/no-equipment-park-workout.jpg',
  'no-equipment-no-excuses-circuit': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/00ba206e-0227-44ee-9409-12ccf00854bd/no-equipment-no-excuses-circuit.jpg',
  'no-equipment-10-minute-no-gear': 'https://healthy-stride-pro.lovable.app/__l5e/assets-v1/d331e0ce-3415-467e-b44c-4bbad3d23dfd/no-equipment-10-minute-no-gear.jpg',
};

String? workoutImageUrl(String workoutId) => workoutImageUrls[workoutId];

// Equipment filters derived from the original Lovable exercise catalogue.
const allEquipment = <String>['None', 'Dumbbells', 'Resistance Band', 'Mat', 'Bench'];
const workoutEquipment = <String, List<String>>{
  'beginner-first-steps': <String>['None', 'Mat'],
  'beginner-beginner-full-body': <String>['Mat', 'None'],
  'beginner-easy-morning-wake-up': <String>['Mat', 'None'],
  'beginner-gentle-strength-start': <String>['Mat', 'None'],
  'beginner-beginner-core-basics': <String>['Mat', 'None'],
  'beginner-low-impact-starter': <String>['None', 'Mat'],
  'beginner-confidence-builder': <String>['Mat', 'None'],
  'beginner-beginner-strength-circuit': <String>['Mat', 'None'],
  'beginner-desk-break-reset': <String>['Mat', 'None'],
  'beginner-beginner-progression': <String>['Mat', 'None'],
  'full-body-total-body-blast': <String>['None', 'Bench', 'Mat'],
  'full-body-full-body-foundations': <String>['None', 'Mat'],
  'full-body-metabolic-full-body': <String>['Mat', 'None'],
  'full-body-30-minute-full-body': <String>['None', 'Mat', 'Bench'],
  'full-body-full-body-power': <String>['None', 'Mat', 'Bench'],
  'full-body-express-full-body': <String>['Mat', 'None', 'Bench'],
  'full-body-strength-endurance-mix': <String>['None', 'Mat'],
  'full-body-full-body-burn': <String>['None', 'Mat'],
  'full-body-balanced-body-circuit': <String>['Mat', 'None'],
  'full-body-weekend-warrior': <String>['Mat', 'None', 'Bench'],
  'cardio-cardio-kickstart': <String>['None'],
  'cardio-hiit-express': <String>['None'],
  'cardio-fat-burn-circuit': <String>['None'],
  'cardio-low-impact-cardio': <String>['None'],
  'cardio-boxing-conditioning': <String>['None'],
  'cardio-sprint-intervals': <String>['None'],
  'cardio-cardio-core-combo': <String>['None'],
  'cardio-morning-heart-starter': <String>['None'],
  'cardio-endurance-builder': <String>['None'],
  'cardio-cardio-finisher': <String>['None'],
  'upper-body-upper-body-basics': <String>['None', 'Bench', 'Mat', 'Resistance Band', 'Dumbbells'],
  'upper-body-push-pull-circuit': <String>['Mat', 'Resistance Band', 'Dumbbells', 'None'],
  'upper-body-dumbbell-upper-body': <String>['Dumbbells', 'None', 'Mat'],
  'upper-body-bodyweight-upper-strength': <String>['None', 'Mat'],
  'upper-body-shoulder-sculpt': <String>['Mat', 'None', 'Bench'],
  'upper-body-upper-body-burnout': <String>['None', 'Bench', 'Mat', 'Resistance Band', 'Dumbbells'],
  'upper-body-posture-builder': <String>['Mat', 'Resistance Band', 'Dumbbells'],
  'upper-body-band-upper-body': <String>['Dumbbells', 'None'],
  'upper-body-chest-and-triceps': <String>['None', 'Mat'],
  'upper-body-back-and-biceps': <String>['Mat', 'None', 'Bench'],
  'lower-body-leg-day-basics': <String>['None', 'Mat'],
  'lower-body-glute-focus': <String>['None', 'Mat'],
  'lower-body-lower-body-strength': <String>['None', 'Mat', 'Dumbbells'],
  'lower-body-quad-burner': <String>['Mat', 'None', 'Dumbbells', 'Resistance Band', 'Bench'],
  'lower-body-hamstrings-and-glutes': <String>['Dumbbells', 'Resistance Band', 'Bench', 'None'],
  'lower-body-bodyweight-leg-circuit': <String>['Bench', 'None', 'Mat'],
  'lower-body-dumbbell-legs': <String>['None', 'Mat'],
  'lower-body-band-lower-body': <String>['None', 'Mat'],
  'lower-body-single-leg-stability': <String>['None', 'Mat', 'Dumbbells'],
  'lower-body-legs-and-calves': <String>['Mat', 'None', 'Dumbbells', 'Resistance Band', 'Bench'],
  'abs-core-core-basics': <String>['Mat'],
  'abs-core-six-pack-circuit': <String>['Mat', 'None'],
  'abs-core-plank-challenge': <String>['Mat'],
  'abs-core-oblique-focus': <String>['Mat'],
  'abs-core-lower-ab-focus': <String>['Mat'],
  'abs-core-core-power': <String>['Mat', 'None'],
  'abs-core-5-minute-abs': <String>['None', 'Mat'],
  'abs-core-standing-core': <String>['Mat'],
  'abs-core-core-stability': <String>['Mat'],
  'abs-core-ab-finisher': <String>['Mat', 'None'],
  'stretching-morning-mobility': <String>['None', 'Mat'],
  'stretching-full-body-stretch': <String>['Mat', 'None'],
  'stretching-post-workout-cooldown': <String>['Mat', 'None'],
  'stretching-lower-body-stretch': <String>['Mat', 'None'],
  'stretching-upper-body-stretch': <String>['Mat', 'None'],
  'stretching-hip-opener-flow': <String>['None', 'Mat'],
  'stretching-back-relief': <String>['Mat', 'None'],
  'stretching-bedtime-wind-down': <String>['None', 'Mat'],
  'stretching-desk-worker-reset': <String>['Mat', 'None'],
  'stretching-deep-flexibility': <String>['None', 'Mat'],
  'chest-chest-builder': <String>['Bench', 'Mat', 'Dumbbells', 'Resistance Band', 'None'],
  'chest-push-up-ladder': <String>['Dumbbells', 'Resistance Band', 'None', 'Bench'],
  'chest-dumbbell-chest': <String>['None', 'Bench', 'Mat', 'Dumbbells'],
  'chest-beginner-chest': <String>['Mat', 'Dumbbells', 'Resistance Band', 'None'],
  'back-strong-back': <String>['Mat', 'Dumbbells'],
  'back-back-without-equipment': <String>['Mat', 'Dumbbells', 'Resistance Band'],
  'back-band-back-session': <String>['Resistance Band', 'Mat'],
  'back-back-strength-builder': <String>['Mat', 'Dumbbells', 'Resistance Band'],
  'arms-arm-sculpt': <String>['Dumbbells', 'None', 'Resistance Band'],
  'arms-bodyweight-arms': <String>['Dumbbells', 'Resistance Band', 'None', 'Bench'],
  'arms-dumbbell-arms': <String>['Dumbbells', 'Bench', 'None'],
  'arms-arm-burnout': <String>['None', 'Dumbbells', 'Resistance Band', 'Bench'],
  'legs-squat-focus': <String>['None', 'Dumbbells', 'Bench'],
  'legs-lunge-matrix': <String>['None', 'Dumbbells', 'Bench'],
  'legs-explosive-legs': <String>['None'],
  'legs-easy-legs': <String>['None', 'Dumbbells'],
  'home-workout-living-room-workout': <String>['Mat', 'None'],
  'home-workout-quiet-apartment-session': <String>['None', 'Mat'],
  'home-workout-home-strength-circuit': <String>['None', 'Mat'],
  'home-workout-hotel-room-workout': <String>['Mat', 'None'],
  'home-workout-family-friendly-moves': <String>['None', 'Mat'],
  'no-equipment-zero-equipment-blast': <String>['None', 'Mat'],
  'no-equipment-anywhere-anytime': <String>['None', 'Mat'],
  'no-equipment-park-workout': <String>['Mat', 'None'],
  'no-equipment-no-excuses-circuit': <String>['None', 'Mat'],
  'no-equipment-10-minute-no-gear': <String>['None'],
};
List<String> equipmentForWorkout(String workoutId) => workoutEquipment[workoutId] ?? const <String>['None'];
