// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDQjduSyV23vnnrzqdAnd-sYPPZ2S2zDiA',
    appId: '1:245792719747:web:88056d769cd732ef39ecb6',
    messagingSenderId: '245792719747',
    projectId: 'fitmalaysia-134fe',
    authDomain: 'fitmalaysia-134fe.firebaseapp.com',
    storageBucket: 'fitmalaysia-134fe.firebasestorage.app',
    measurementId: 'G-GX1D29PBJ3',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyD3DETSnjxoHzLuU65MDUC5W4c37uyZImM',
    appId: '1:245792719747:android:6af615f90c297db239ecb6',
    messagingSenderId: '245792719747',
    projectId: 'fitmalaysia-134fe',
    storageBucket: 'fitmalaysia-134fe.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBhTZA_FOqaN73QqCtuGFV2Uxsc8rOTBX4',
    appId: '1:245792719747:ios:f3006d49670e640039ecb6',
    messagingSenderId: '245792719747',
    projectId: 'fitmalaysia-134fe',
    storageBucket: 'fitmalaysia-134fe.firebasestorage.app',
    iosBundleId: 'com.example.fitmalaysia',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBhTZA_FOqaN73QqCtuGFV2Uxsc8rOTBX4',
    appId: '1:245792719747:ios:f3006d49670e640039ecb6',
    messagingSenderId: '245792719747',
    projectId: 'fitmalaysia-134fe',
    storageBucket: 'fitmalaysia-134fe.firebasestorage.app',
    iosBundleId: 'com.example.fitmalaysia',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDQjduSyV23vnnrzqdAnd-sYPPZ2S2zDiA',
    appId: '1:245792719747:web:82fa20438afb8df139ecb6',
    messagingSenderId: '245792719747',
    projectId: 'fitmalaysia-134fe',
    authDomain: 'fitmalaysia-134fe.firebaseapp.com',
    storageBucket: 'fitmalaysia-134fe.firebasestorage.app',
    measurementId: 'G-CQ69PZN742',
  );
}
